version: '3'
services:

  redis: 
    container_name: redis-server
    image: 'redis:latest'

  node-app:
    container_name: node-app1
    build: . 
    ports: 
      - "80": "8081"
networks:
  redis-nodejs:
    driver: brige 
    name: redis-nodejs 
    ipam:
      config: 
        - subnet: 172.19.0.0/26

